language: node_js
node_js:
  - 10.16
install:
  - npm install
jobs:
  include:
    - stage: test
      script: 
        - npm run lint
        - npm run test
    - stage: master
      if: branch = master
      script:
        - npm run test
        - npm run coveralls
        - npm run version

  
